### PR TITLE
Update lints to work with Rust 1.67

### PR DESCRIPTION
**Pull request by deg4uss3r**
fixes CI

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Did this code not work with rust 1.67 before the patch?

**Comment by deg4uss3r** [comment]
It worked but this is the new recommended way to format strings with rags and was failing `cargo clippy`.

**Comment by matthiasbeyer** [comment]
Ah okay, I think I was confused by the commit message.

**Comment by deg4uss3r** [comment]
Sorry @matthiasbeyer, I'll do better in the future to make merges like this very clear!

**Pull request merged**
